	/* ソート順の初期調整 */
	update SPTMT_SP_MENU_SORT set SORT = SORT + 2 where SORT > 6;
	
	--契約0の初期データ
	insert into SPTMT_STANDARD_MENU (INS_DATE,INS_CCD,INS_SCD,INS_PG,UPD_DATE,UPD_CCD,UPD_SCD,UPD_PG,EXCLUS_VER,CONTRACT_CD,CID,SYSTEM,MENU_CLS,CODE,MENU_ATR,TARGET_ITEMS,DISPLAY_NAME,DISPLAY_ORDER,PROGRAM_ID,SCREEN_ID,QUERY_STRING,URL,WEB_MENU_SETTING,AFTER_LOGIN_DISPLAY,LOG_LOGIN_DISPLAY,LOG_START_DISPLAY,LOG_UPDATE_DISPLAY) values (null,null,null,null,null,null,null,null,0,'000000000000','000000000000-0000',1,9,'0025',0,'月別実績の修正','月別実績の修正',25,'KMWS03','A','displayformat=0','/nts.uk.mobile.web/kmw/s03/a',0,0,0,1,0);
	insert into SPTMT_STANDARD_MENU (INS_DATE,INS_CCD,INS_SCD,INS_PG,UPD_DATE,UPD_CCD,UPD_SCD,UPD_PG,EXCLUS_VER,CONTRACT_CD,CID,SYSTEM,MENU_CLS,CODE,MENU_ATR,TARGET_ITEMS,DISPLAY_NAME,DISPLAY_ORDER,PROGRAM_ID,SCREEN_ID,QUERY_STRING,URL,WEB_MENU_SETTING,AFTER_LOGIN_DISPLAY,LOG_LOGIN_DISPLAY,LOG_START_DISPLAY,LOG_UPDATE_DISPLAY) values (null,null,null,null,null,null,null,null,0,'000000000000','000000000000-0000',1,9,'0026',0,'月別実績の確認','月別実績の確認',26,'KMWS03','A','displayformat=1','/nts.uk.mobile.web/kmw/s03/a',0,0,0,1,0);

	insert into SPTMT_SP_MENU_SORT (INS_DATE,INS_CCD,INS_SCD,INS_PG,UPD_DATE,UPD_CCD,UPD_SCD,UPD_PG,EXCLUS_VER,CONTRACT_CD,CID,CODE,SORT) values (null,null,null,null,null,null,null,null,0,'000000000000','000000000000-0000','0025',7);
	insert into SPTMT_SP_MENU_SORT (INS_DATE,INS_CCD,INS_SCD,INS_PG,UPD_DATE,UPD_CCD,UPD_SCD,UPD_PG,EXCLUS_VER,CONTRACT_CD,CID,CODE,SORT) values (null,null,null,null,null,null,null,null,0,'000000000000','000000000000-0000','0026',8);

	DECLARE @CONTRACT_CD_SF CHAR(12);
	DECLARE @CID_SF         CHAR(17);

	SET @CONTRACT_CD_SF = '000000000000';                          --ここの初期値は、どんな値をいれているかをみえるようにしているだけです。
	SET @CID_SF         = '000000000000-0000';

	DECLARE crTriggerList CURSOR FOR
	   select CONTRACT_CD,CID from BCMMT_COMPANY ;    -- 全ての契約、会社でLoopする

	OPEN crTriggerList;

	FETCH NEXT FROM crTriggerList
	INTO @CONTRACT_CD_SF, @CID_SF;

	WHILE @@FETCH_STATUS = 0
	BEGIN

		--PRINT @CID_SF

		IF NOT EXISTS (SELECT CONTRACT_CD, CID FROM SPTMT_STANDARD_MENU WHERE CONTRACT_CD=@CONTRACT_CD_SF AND CID=@CID_SF AND MENU_CLS = 9 AND DISPLAY_ORDER = 25)
		BEGIN
			insert into SPTMT_STANDARD_MENU (INS_DATE,INS_CCD,INS_SCD,INS_PG,UPD_DATE,UPD_CCD,UPD_SCD,UPD_PG,EXCLUS_VER,CONTRACT_CD,CID,SYSTEM,MENU_CLS,CODE,MENU_ATR,TARGET_ITEMS,DISPLAY_NAME,DISPLAY_ORDER,PROGRAM_ID,SCREEN_ID,QUERY_STRING,URL,WEB_MENU_SETTING,AFTER_LOGIN_DISPLAY,LOG_LOGIN_DISPLAY,LOG_START_DISPLAY,LOG_UPDATE_DISPLAY) values (null,null,null,null,null,null,null,null,0,@CONTRACT_CD_SF,@CID_SF,1,9,'0025',0,'月別実績の修正','月別実績の修正',25,'KMWS03','A','displayformat=0','/nts.uk.mobile.web/kmw/s03/a',0,0,0,1,0);
			insert into SPTMT_STANDARD_MENU (INS_DATE,INS_CCD,INS_SCD,INS_PG,UPD_DATE,UPD_CCD,UPD_SCD,UPD_PG,EXCLUS_VER,CONTRACT_CD,CID,SYSTEM,MENU_CLS,CODE,MENU_ATR,TARGET_ITEMS,DISPLAY_NAME,DISPLAY_ORDER,PROGRAM_ID,SCREEN_ID,QUERY_STRING,URL,WEB_MENU_SETTING,AFTER_LOGIN_DISPLAY,LOG_LOGIN_DISPLAY,LOG_START_DISPLAY,LOG_UPDATE_DISPLAY) values (null,null,null,null,null,null,null,null,0,@CONTRACT_CD_SF,@CID_SF,1,9,'0026',0,'月別実績の確認','月別実績の確認',26,'KMWS03','A','displayformat=1','/nts.uk.mobile.web/kmw/s03/a',0,0,0,1,0);

			insert into SPTMT_SP_MENU_SORT (INS_DATE,INS_CCD,INS_SCD,INS_PG,UPD_DATE,UPD_CCD,UPD_SCD,UPD_PG,EXCLUS_VER,CONTRACT_CD,CID,CODE,SORT) values (null,null,null,null,null,null,null,null,0,@CONTRACT_CD_SF,@CID_SF,'0025',7);
			insert into SPTMT_SP_MENU_SORT (INS_DATE,INS_CCD,INS_SCD,INS_PG,UPD_DATE,UPD_CCD,UPD_SCD,UPD_PG,EXCLUS_VER,CONTRACT_CD,CID,CODE,SORT) values (null,null,null,null,null,null,null,null,0,@CONTRACT_CD_SF,@CID_SF,'0026',8);

		END
	
	    FETCH NEXT FROM crTriggerList
	    INTO @CONTRACT_CD_SF, @CID_SF;
	END

	CLOSE crTriggerList;
	DEALLOCATE crTriggerList;


GO