/* ソート順の初期調整 */
update SPTMT_SP_MENU_SORT set SORT = SORT + 2 where SORT > 6;

/* スマホメニュー　月別の0会社データ */

insert into SPTMT_STANDARD_MENU (INS_DATE,INS_CCD,INS_SCD,INS_PG,UPD_DATE,UPD_CCD,UPD_SCD,UPD_PG,EXCLUS_VER,CONTRACT_CD,CID,SYSTEM,MENU_CLS,CODE,MENU_ATR,TARGET_ITEMS,DISPLAY_NAME,DISPLAY_ORDER,PROGRAM_ID,SCREEN_ID,QUERY_STRING,URL,WEB_MENU_SETTING,AFTER_LOGIN_DISPLAY,LOG_LOGIN_DISPLAY,LOG_START_DISPLAY,LOG_UPDATE_DISPLAY) values (null,null,null,null,null,null,null,null,0,'000000000000','000000000000-0000',1,9,'0025',0,'月別実績の修正','月別実績の修正',25,'KMWS03','A','displayformat=0','/nts.uk.mobile.web/kmw/s03/a',0,0,0,1,0);
insert into SPTMT_STANDARD_MENU (INS_DATE,INS_CCD,INS_SCD,INS_PG,UPD_DATE,UPD_CCD,UPD_SCD,UPD_PG,EXCLUS_VER,CONTRACT_CD,CID,SYSTEM,MENU_CLS,CODE,MENU_ATR,TARGET_ITEMS,DISPLAY_NAME,DISPLAY_ORDER,PROGRAM_ID,SCREEN_ID,QUERY_STRING,URL,WEB_MENU_SETTING,AFTER_LOGIN_DISPLAY,LOG_LOGIN_DISPLAY,LOG_START_DISPLAY,LOG_UPDATE_DISPLAY) values (null,null,null,null,null,null,null,null,0,'000000000000','000000000000-0000',1,9,'0026',0,'月別実績の確認','月別実績の確認',26,'KMWS03','A','displayformat=1','/nts.uk.mobile.web/kmw/s03/a',0,0,0,1,0);

insert into SPTMT_SP_MENU_SORT (INS_DATE,INS_CCD,INS_SCD,INS_PG,UPD_DATE,UPD_CCD,UPD_SCD,UPD_PG,EXCLUS_VER,CONTRACT_CD,CID,CODE,SORT) values (null,null,null,null,null,null,null,null,0,'000000000000','000000000000-0000','0025',7);
insert into SPTMT_SP_MENU_SORT (INS_DATE,INS_CCD,INS_SCD,INS_PG,UPD_DATE,UPD_CCD,UPD_SCD,UPD_PG,EXCLUS_VER,CONTRACT_CD,CID,CODE,SORT) values (null,null,null,null,null,null,null,null,0,'000000000000','000000000000-0000','0026',8);

/* copy data*/
do $$ 
   	declare cursorList CURSOR FOR 
   		select CONTRACT_CD, CID from BCMMT_COMPANY;
   		companyRecord RECORD;
		
		
begin
	open cursorList;
   	loop
			
			fetch cursorList into companyRecord;

			exit when not found;
			
			insert into SPTMT_STANDARD_MENU (INS_DATE,INS_CCD,INS_SCD,INS_PG,UPD_DATE,UPD_CCD,UPD_SCD,UPD_PG,EXCLUS_VER,CONTRACT_CD,CID,SYSTEM,MENU_CLS,CODE,MENU_ATR,TARGET_ITEMS,DISPLAY_NAME,DISPLAY_ORDER,PROGRAM_ID,SCREEN_ID,QUERY_STRING,URL,WEB_MENU_SETTING,AFTER_LOGIN_DISPLAY,LOG_LOGIN_DISPLAY,LOG_START_DISPLAY,LOG_UPDATE_DISPLAY) values (null,null,null,null,null,null,null,null,0,companyRecord.CONTRACT_CD,companyRecord.CID,1,9,'0025',0,'月別実績の修正','月別実績の修正',25,'KMWS03','A','displayformat=0','/nts.uk.mobile.web/kmw/s03/a',0,0,0,1,0);
			insert into SPTMT_STANDARD_MENU (INS_DATE,INS_CCD,INS_SCD,INS_PG,UPD_DATE,UPD_CCD,UPD_SCD,UPD_PG,EXCLUS_VER,CONTRACT_CD,CID,SYSTEM,MENU_CLS,CODE,MENU_ATR,TARGET_ITEMS,DISPLAY_NAME,DISPLAY_ORDER,PROGRAM_ID,SCREEN_ID,QUERY_STRING,URL,WEB_MENU_SETTING,AFTER_LOGIN_DISPLAY,LOG_LOGIN_DISPLAY,LOG_START_DISPLAY,LOG_UPDATE_DISPLAY) values (null,null,null,null,null,null,null,null,0,companyRecord.CONTRACT_CD,companyRecord.CID,1,9,'0026',0,'月別実績の確認','月別実績の確認',26,'KMWS03','A','displayformat=1','/nts.uk.mobile.web/kmw/s03/a',0,0,0,1,0);

			insert into SPTMT_SP_MENU_SORT (INS_DATE,INS_CCD,INS_SCD,INS_PG,UPD_DATE,UPD_CCD,UPD_SCD,UPD_PG,EXCLUS_VER,CONTRACT_CD,CID,CODE,SORT) values (null,null,null,null,null,null,null,null,0,companyRecord.CONTRACT_CD,companyRecord.CID,'0025',7);
			insert into SPTMT_SP_MENU_SORT (INS_DATE,INS_CCD,INS_SCD,INS_PG,UPD_DATE,UPD_CCD,UPD_SCD,UPD_PG,EXCLUS_VER,CONTRACT_CD,CID,CODE,SORT) values (null,null,null,null,null,null,null,null,0,companyRecord.CONTRACT_CD,companyRecord.CID,'0026',8);

   	end loop;

   close cursorList;
   
end $$;